name: factoryflow
description: FactoryFlow - Factory Management System
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  pdf: ^3.11.0
  printing: ^5.14.3
  excel: ^2.1.0
  share_plus: ^13.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  crypto: ^3.0.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
